CREATE TABLE IF NOT EXISTS bouquets (
  id SERIAL PRIMARY KEY,
  "photoURL" VARCHAR(255) NOT NULL,
  "image2x" VARCHAR(255),
  alt VARCHAR(255),
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price VARCHAR(50) NOT NULL,
  favorite BOOLEAN DEFAULT false,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
